name: CI

on:
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ci-${{ github.event.pull_request.title }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-commits:
    name: Lint Commits
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - uses: wagoid/commitlint-github-action@v5
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

  lint-styles:
    name: Lint Styles
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Run lint script
        run: npm run lint
